# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'LoveHouse' do
pod 'AVOSCloud'               # 数据存储、短信、云引擎调用等基础服务模块
pod 'AVOSCloudCrashReporting' # 错误报告模块
pod 'DGActivityIndicatorView'
pod 'ChameleonFramework'
pod 'ECSlidingViewController', '~> 2.0.3'
pod 'Masonry'

pod 'CocoaLumberjack', '~>2.2.0'
pod 'WordPress-iOS-Shared', '~>0.5.0'
pod 'WordPressCom-Analytics-iOS'

end
